### PR TITLE
Increased error bound to solve issue #25

### PR DESCRIPTION
**Pull request by PJ-Prins**
See https://github.com/FastNFT/FNFT/issues/25

### CODE REVIEW

**Comment by PJ-Prins** [comment]
For me, running `fnft__akns_fscatter_test_2split6A` with or without FFTW makes a difference of 40% in the error, so please check whether the test passes both with and without FFTW enabled.

**Review by ShrinivasJC — APPROVED** [review]

**Comment by marbre** [comment]
The test passes on my machine now.

*With FFTW:*
```
14: error without normalization = 3.5e-14 < 6.5e-14
14: error with normalization = 3.5e-14 < 6.5e-14
1/1 Test #14: fnft__akns_fscatter_test_2split6A ...   Passed    0.00 sec
```

*Without FFTW:*
```
14: error without normalization = 6.4e-14 < 6.5e-14
14: error with normalization = 6.4e-14 < 6.5e-14
1/1 Test #14: fnft__akns_fscatter_test_2split6A ...   Passed    0.00 sec
```

**Comment by PJ-Prins** [comment]
Thank you, @marbre .

**Review by wahls — APPROVED** [review]
Works for me with and without FFTW.

One comment for the future. Since the bound is used four times, it would be better to declare a constant holding its value. That makes changing it simpler and less error-prone.

**Pull request merged**
