### PR TITLE
Inverse NFT of NSE with discrete spectrum

### PR DESCRIPTION
**Pull request by ShrinivasJC**
Check for missing/incorrect documentation.

### CODE REVIEW

**Review by wahls — APPROVED** [review]
All tests pass. Doxygen proceeds without errors as well.

**Review by PJ-Prins — CHANGES_REQUESTED** [review]
I've tested with gcc and clang, both with and without fftw. All tests pass with gcc, but two tests fail with clang. Fftw makes no difference. Debug output:

(...) /FNFT/test/fnft_nsev_inverse/fnft_nsev_inverse_test_B_of_tau_or_b_of_xi/fnft_nsev_inverse_test_b_of_xi_2split2_modal ; exit;
error = 0.00129808
error = 0.00129808
error = 0.000323153
error = 0.000323153
error = 8.06212e-05
error = 1
FNFT Error: Test failed.
 in fnft_nsev_inverse_test(97)-0.1.1-dev
FNFT Error: Subroutine failure.
 in main(36)-0.1.1-dev
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Proces voltooid]

(...) /FNFT/test/fnft_nsev_inverse/fnft_nsev_inverse_test_B_of_tau_or_b_of_xi/fnft_nsev_inverse_test_b_of_xi_2split2A ; exit;
error = 0.000823486
error = 0.000823486
error = 0.000205697
error = 0.000205697
error = 5.13109e-05
error = 1
FNFT Error: Test failed.
 in fnft_nsev_inverse_test(97)-0.1.1-dev
FNFT Error: Subroutine failure.
 in main(36)-0.1.1-dev
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Proces voltooid]

**Comment by wahls** [comment]
@PJ-Prins, which version of clang did you use? It passes for clang 6.0.1 on my machine.

**Comment by PJ-Prins** [comment]
@wahls, `clang --version` tells me `Apple LLVM version 9.1.0 (clang-902.0.39.2)`.

**Review by PJ-Prins — APPROVED** [review]

**Pull request merged**
