### PR TITLE
Release 0.1

### PR DESCRIPTION
**Pull request by wahls**
Mex files should now compile with Matlab R2018a. Also fixed several bugs.

### CODE REVIEW

**Comment by ShrinivasJC** [comment]
Shouldn't development branch also be updated as this involves fixes to bugs which potentially also exist in the development branch?

**Review by ShrinivasJC — APPROVED** [review]

**Comment by wahls** [comment]
Yes. Some of them are already there. Will merge into development after this.

Did you have a chance to test R2018a?

**Comment by ShrinivasJC** [comment]
No, I am still working with R2017b.

**Comment by PJ-Prins** [comment]
On Mac with *only* R2018a installed, cmake gives the following error: 'Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR MX_LIBRARY) (found version "NOTFOUND")'
If R2017b is installed in parallel to R2018a, compilation works (apparently using R2017b) and then the mex file file examples run in R2018a as well.

**Review by PJ-Prins — APPROVED** [review]
Works if cmake is called with -DMatlab_ROOT_DIR=/Applications/MATLAB_R2018a.app and using gcc

**Pull request merged**
