### PR TITLE
Make building tests optional (default set to ON)

### PR DESCRIPTION
**Pull request by marbre**

### CODE REVIEW

**Comment by wahls** [comment]
Dear Marius,

Thank you for your contribution.

This is indeed a good idea, but could I ask you to please make two changes:

1) Could you please modify the development branch instead of master? We are (more or less) trying to follow [GitFlow](https://nvie.com/posts/a-successful-git-branching-model/?).

2) I see that we have not yet added a license header to the CMake file. Could you please add the header below and add yourself to the list of contributors? We use the convention that if we are not acting as private persons, but as employees, we add the university name in brackets. In the latter case, please check that you are allowed to contribute to FNFT under the terms of the GPLv2.
```
# This file is part of FNFT.
#
# FNFT is free software; you can redistribute it and/or
# modify it under the terms of the version 2 of the GNU General
# Public License as published by the Free Software Foundation.
#
# FNFT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Contributors:
# Sander Wahls (TU Delft) 2017-2018.
```
Best, Sander

**Comment by marbre** [comment]
@wahls All Done.

Btw, should spaces or tabs be used in the CMakeLists? At the moment it's mixed.

**Comment by wahls** [comment]
It looks as if the first call to enable_testing() in
```
enable_testing()
if (BUILD_TESTS)
	enable_testing()
endif()
```
should not be there, should it?

About the spaces: Good question ... I prefer spaces, but we do not have a policy.

**Comment by marbre** [comment]
You're correct, I was too fast with rebasing on the development branch. Have fixed this now and deleted the `enable_testing()` prior to the if clause. Thanks for the careful review.

**Review by wahls — APPROVED** [review]
Works fine.

**Pull request merged**
