### PR TITLE
Feature fft wrapper

### PR DESCRIPTION
**Pull request by wahls**
I added a wrapper around the FFT routine we had so far and added support for FFTW. CMake should now use FFTW automatically when it is available and fall back to Kiss FFT otherwise.

Could you install FFTW (Ubuntu: sudo apt-install libfftw3-dev , MacOS: brew install fftw), test it, and report any issues or other comments back here?

### CODE REVIEW

**Comment by ShrinivasJC** [comment]
Feature complies and works on Ubuntu.

**Comment by PJ-Prins** [comment]
After running make:
```
(...)
[ 41%] Linking Fortran shared library ../lib/libfnft.dylib
Undefined symbols for architecture x86_64:
  "_fftw_destroy_plan", referenced from:
      _fnft__poly_chirpz in fnft__poly_chirpz.c.o
      _fnft__poly_fmult in fnft__poly_fmult.c.o
      _fnft__poly_fmult2x2 in fnft__poly_fmult.c.o
  "_fftw_execute_dft", referenced from:
      _fnft__poly_chirpz in fnft__poly_chirpz.c.o
      _poly_fmult2 in fnft__poly_fmult.c.o
  "_fftw_free", referenced from:
      _fnft__poly_chirpz in fnft__poly_chirpz.c.o
      _fnft__poly_fmult in fnft__poly_fmult.c.o
      _fnft__poly_fmult2x2 in fnft__poly_fmult.c.o
  "_fftw_malloc", referenced from:
      _fnft__poly_chirpz in fnft__poly_chirpz.c.o
      _fnft__poly_fmult in fnft__poly_fmult.c.o
      _fnft__poly_fmult2x2 in fnft__poly_fmult.c.o
  "_fftw_plan_dft_1d", referenced from:
      _fnft__poly_chirpz in fnft__poly_chirpz.c.o
      _fnft__poly_fmult in fnft__poly_fmult.c.o
      _fnft__poly_fmult2x2 in fnft__poly_fmult.c.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [../lib/libfnft.dylib] Error 1
make[1]: *** [CMakeFiles/fnft.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ShrinivasJC** [comment]
Thread about similar issue. 

https://github.com/FFTW/fftw3/issues/10

**Comment by wahls** [comment]
I think I fixed it. Peter, could you please give it another try?

The FFTW support is now opt-in and not opt-out. You therefore have to run

cmake .. -DENABLE_FFTW=ON

**Review by PJ-Prins — APPROVED** [review]
Working.

**Review by ShrinivasJC — APPROVED** [review]
Feature complies and runs as expected

**Pull request merged**
