### PR TITLE
Add make install support

### PR DESCRIPTION
**Pull request by marbre**
This installs the public headers to `include` and a versioned *.so files to `lib`.  
- The prefix can be chosen by setting `DESTDIR` [[1](https://gitlab.kitware.com/cmake/community/wikis/FAQ#does-cmakes-make-install-support-destdir),[2](https://cmake.org/cmake/help/v3.12/envvar/DESTDIR.html#envvar:DESTDIR)].  
- By default cmake does not provide `make uninstall` [[3](https://gitlab.kitware.com/cmake/community/wikis/FAQ#can-i-do-make-uninstall-with-cmake)].

### CODE REVIEW

**Comment by marbre** [comment]
Instead of the `DESTDIR` one might pass `-DCMAKE_INSTALL_PREFIX` to the cmake call. Whereas [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) just changes the prefix, `DESTDIR` will relocate the whole installation.

**Review by wahls — APPROVED** [review]
Thanks much, it works fine.

I had to fix a few public headers that included private ones. I also added a suffix to the version so that we can distinguish real releases from development version. 

I will ask for another review of the updated version.

**Comment by wahls** [comment]
@ShrinivasJC, @PJ-Prins, could you please try https://github.com/marbre/FNFT/tree/cmake ?

I updated INSTALL.md, there is now a description of how to perform a system-wide installation.

If successful, you should be able to rebuild the examples as follows:
```
[sander@sander-pc FNFT-cmake]$ cd examples/
[sander@sander-pc examples]$ rm fnft_nsev_example
[sander@sander-pc examples]$ gcc -o fnft_nsev_example fnft_nsev_example.c -lfnft
[sander@sander-pc examples]$ ./fnft_nsev_example 
Number of samples:
  D = 256
Continuous spectrum:
  continuous_spectrum(xi=-2.000000) 	= -0.105386 + -0.425771I
  continuous_spectrum(xi=-1.428571) 	= -0.78378 + -1.04297I
  continuous_spectrum(xi=-0.857143) 	= -1.0909 + -1.33957I
  continuous_spectrum(xi=-0.285714) 	= -1.16919 + -0.483252I
  continuous_spectrum(xi=0.285714) 	= -1.16919 + 0.483252I
  continuous_spectrum(xi=0.857143) 	= -1.0909 + 1.33957I
  continuous_spectrum(xi=1.428571) 	= -0.78378 + 1.04297I
  continuous_spectrum(xi=2.000000) 	= -0.105386 + 0.425771I
Discrete spectrum:
  bound state at 0 + 1.57423I with norming constant -1 + 0I
 ```

**Comment by wahls** [comment]
@ShrinivasJC , @PJ-Prins , could you please try the system-wide installation described in the updated INSTALL.md in https://github.com/marbre/FNFT/tree/cmake ?

If successful, you should be able to rebuild the examples like this:

```
[sander@sander-pc FNFT-cmake]$ cd examples/
[sander@sander-pc examples]$ rm fnft_nsev_example
[sander@sander-pc examples]$ gcc -o fnft_nsev_example fnft_nsev_example.c -lfnft
[sander@sander-pc examples]$ ./fnft_nsev_example 
Number of samples:
  D = 256
Continuous spectrum:
  continuous_spectrum(xi=-2.000000) 	= -0.105386 + -0.425771I
  continuous_spectrum(xi=-1.428571) 	= -0.78378 + -1.04297I
  continuous_spectrum(xi=-0.857143) 	= -1.0909 + -1.33957I
  continuous_spectrum(xi=-0.285714) 	= -1.16919 + -0.483252I
  continuous_spectrum(xi=0.285714) 	= -1.16919 + 0.483252I
  continuous_spectrum(xi=0.857143) 	= -1.0909 + 1.33957I
  continuous_spectrum(xi=1.428571) 	= -0.78378 + 1.04297I
  continuous_spectrum(xi=2.000000) 	= -0.105386 + 0.425771I
Discrete spectrum:
  bound state at 0 + 1.57423I with norming constant -1 + 0I
```

**Comment by ShrinivasJC** [comment]
@wahls Following all the instructions I get the following error

 nft@nft-Latitude-E7450:~/Documents/codes/software_test/FNFT/examples$ rm fnft_nsev_example
rm: remove write-protected regular file 'fnft_nsev_example'? 
nft@nft-Latitude-E7450:~/Documents/codes/software_test/FNFT/examples$ ls
fnft_kdvv_example    fnft_nsev_example.c          mex_fnft_nsev_example.m
fnft_kdvv_example.c  fnft_nsev_inverse_example    mex_fnft_nsev_inverse_example_1.m
fnft_nsep_example    fnft_nsev_inverse_example.c  mex_fnft_nsev_inverse_example_2_exact_solution.m
fnft_nsep_example.c  mex_fnft_kdvv_example.m      mex_fnft_nsev_inverse_example_2.m
fnft_nsev_example    mex_fnft_nsep_example.m      mex_fnft_nsev_inverse_example_3.m
nft@nft-Latitude-E7450:~/Documents/codes/software_test/FNFT/examples$ gcc -o fnft_nsev_example fnft_nsev_example.c -lfnft
nft@nft-Latitude-E7450:~/Documents/codes/software_test/FNFT/examples$ ./fnft_nsev_example
./fnft_nsev_example: error while loading shared libraries: libfnft.so.0: cannot open shared object file: No such file or directory
nft@nft-Latitude-E7450:~/Documents/codes/software_test/FNFT/examples$

**Comment by PJ-Prins** [comment]
I get the following error:
$ gcc -o fnft_nsev_example fnft_nsev_example.c -lfnft
fnft_nsev_example.c:27:10: fatale fout: fnft_nsev.h: No such file or directory

**Comment by wahls** [comment]
Could you both please try
```
gcc -o fnft_nsev_example fnft_nsev_example.c -lfnft -I/usr/local/include -L/usr/local/lib
```

**Comment by PJ-Prins** [comment]
Same result:

$ gcc -o fnft_nsev_example fnft_nsev_example.c -lfnft -I/usr/local/include -L/usr/local/lib
fnft_nsev_example.c:27:10: fatale fout: fnft_nsev.h: No such file or directory

**Comment by ShrinivasJC** [comment]
Same result

nft@nft-Latitude-E7450:~/Documents/codes/software_test/FNFT/examples$ gcc -o fnft_nsev_example fnft_nsev_example.c -lfnft -I/usr/local/include -L/usr/local/lib
nft@nft-Latitude-E7450:~/Documents/codes/software_test/FNFT/examples$ ./fnft_nsev_example
./fnft_nsev_example: error while loading shared libraries: libfnft.so.0: cannot open shared object file: No such file or directory

**Comment by wahls** [comment]
@PJ-Prins , there should be a file called 'install_manifest.txt' in the build directory.

Could you please post it?

**Comment by PJ-Prins** [comment]
I'm sorry, but there is no file with that name, neither in the build folder, nor anywhere else on my harddrive.

**Comment by wahls** [comment]
Did you run
```
sudo make install
```
Which output did you get?

**Comment by ShrinivasJC** [comment]
I have install_manifest.txt

/usr/local/lib/libfnft.so.0.1.1-dev
/usr/local/lib/libfnft.so.0
/usr/local/lib/libfnft.so
/usr/local/include/fnft_numtypes.h
/usr/local/include/fnft.h
/usr/local/include/fnft_nsev_inverse.h
/usr/local/include/fnft_nsev.h
/usr/local/include/fnft_kdvv.h
/usr/local/include/fnft_nsep.h
/usr/local/include/fnft_nse_discretization_t.h
/usr/local/include/fnft_config.h
/usr/local/include/fnft_kdv_discretization_t.h
/usr/local/include/fnft_errwarn.h

**Comment by marbre** [comment]
With the latest commit one should get an install_mainfest.txt like this:
```
/usr/local/lib/libfnft.so.0.1.1-dev
/usr/local/lib/libfnft.so.0
/usr/local/lib/libfnft.so
/usr/local/include/fnft.h
/usr/local/include/fnft_config.h
/usr/local/include/fnft_errwarn.h
/usr/local/include/fnft_kdv_discretization_t.h
/usr/local/include/fnft_kdvv.h
/usr/local/include/fnft_nse_discretization_t.h
/usr/local/include/fnft_nsep.h
/usr/local/include/fnft_nsev.h
/usr/local/include/fnft_nsev_inverse.h
/usr/local/include/fnft_numtypes.h
```

Anyway, same here with the examples. I am somehow confused why this happens, the elf header of the shared object looks fine.

**Comment by wahls** [comment]
It works for me, but I guess it depends on the distribution...

Could you try again after running
```
sudo ldconfig
```
If that does not help, try
```
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
```

**Comment by marbre** [comment]
Might be that Gentoo doesn't searches within `/usr/local/lib/`. Works with setting the `LD_LIBRARY_PATH`: 
```
brehler@manakov ~/Development/FNFT/examples $ LD_LIBRARY_PATH=/usr/local/lib ldd fnft_nsev_example
        linux-vdso.so.1 (0x00007ffcc7f86000)
        libfnft.so.0 => /usr/local/lib/libfnft.so.0 (0x00007fe927a94000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe9276d2000)
        libfftw3.so.3 => /usr/lib64/libfftw3.so.3 (0x00007fe927226000)
        libgfortran.so.3 => /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/libgfortran.so.3 (0x00007fe926ef5000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe926bb2000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libgcc_s.so.1 (0x00007fe92699b000)
        libquadmath.so.0 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libquadmath.so.0 (0x00007fe92675b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe927eef000)
brehler@manakov ~/Development/FNFT/examples $ LD_LIBRARY_PATH=/usr/local/lib ./fnft_nsev_example
Number of samples:
  D = 256
Continuous spectrum:
  continuous_spectrum(xi=-2.000000)  = -0.105386 + -0.425771I
  continuous_spectrum(xi=-1.428571)  = -0.78378 + -1.04297I
  continuous_spectrum(xi=-0.857143)  = -1.0909 + -1.33957I
  continuous_spectrum(xi=-0.285714)  = -1.16919 + -0.483252I
  continuous_spectrum(xi=0.285714)   = -1.16919 + 0.483252I
  continuous_spectrum(xi=0.857143)   = -1.0909 + 1.33957I
  continuous_spectrum(xi=1.428571)   = -0.78378 + 1.04297I
  continuous_spectrum(xi=2.000000)   = -0.105386 + 0.425771I
Discrete spectrum:
  bound state at 1.67048e-52 + 1.57423I with norming constant -1 + -2.00584e-52I
```

**Comment by PJ-Prins** [comment]
Sorry, I followed the instructions under "Building under MacOS" and didn't notice the last 4 lines of INSTALL.md. Now it works.

**Comment by ShrinivasJC** [comment]
Running

`sudo ldconfig`

fixes the problem for me.

**Comment by wahls** [comment]
I added "sudo ldconfig" to INSTALL.md.

@PJ-Prins @ShrinivasJC Any other issues and/or comments?

**Comment by PJ-Prins** [comment]
Does this apply to Windows as well? In that case the instructions are missing from INSTALL.md.

(Furthermore "Customization" is currently only mentioned for Linux.)

**Comment by wahls** [comment]
I do not expect this to work under Windows (at least not in a straight-forward way). Since this is a non-essential feature, I propose to skip it on that platform.

"Customization" is also mentioned for MacOS:
```
System-wide installation and customization

Please read the instructions for Linux systems above.
```
(Note the heading.)

**Review by ShrinivasJC — APPROVED** [review]

**Comment by PJ-Prins** [comment]
Then I would remove the Windows-specific information about system-wide installation in Building under Linux/customization, to avoid confusion about whether or not it is supported: 
"During a system-wide installation, FNFT is by default installed in (...) 'c:\Program Files\FNFT' on Windows."

**Review by PJ-Prins — APPROVED** [review]

**Comment by wahls** [comment]
Good point,, I changed that.

Thanks, everyone!

**Pull request merged**
