### PR TITLE
Fixed

### PR DESCRIPTION
**Pull request by PJ-Prins**
Made intended type casts explicit (to be able henceforth to detect unintended type casts) and added some overflow checks.
Solved the use of a possibly uninitialised pointer in `fnft__akns_scatter_matrix.c`.

### CODE REVIEW

**Review by ShrinivasJC — APPROVED** [review]
Complies without warnings and all tests pass using GCC 7.5.0. 
Please add as a comment here the compilers that you have tested on Mac OS.

**Comment by PJ-Prins** [comment]
I've tested on MacOS with GCC 10.2.0 as well as Apple clang version 11.0.0, all tests pass.

**Comment by wahls** [comment]
Compiles fine on Linux with GCC 10.2. All tests pass.

I was wondering why the kiss_fft files had to be changed? In any case, it would good to place a comment at the top of these files to indicate that these are modifications of the original files.

In `akns_fscatter`, I see a lot of for loops like this: `for (i=((INT)D)-1; i>=0; i--)`. Why not make `i` a `UINT` instead? The right way to write the for loop in such cases is `for (i=D-1; --i>0;)`, I believe.

**Comment by PJ-Prins** [comment]
The kiss_fft files contained a lot of `int`'s for variables that should never take negative values. Hence, you normally call it with an `unsigned int` for such values, leading to an implicit type cast. I'm not sure if the range between `INT_MAX` and `UINT_MAX` is ever needed and usable in practice with the current solution. If not, an alternative solution would be a type cast with overflow check at every call of a kiss_fft function.

Regarding the loops: The reason is that if `i` is unsigned, `i>=0` always remains true, so the loops never end. This ugly solution just makes the previous implicit type cast explicit. If it can be solved in a prettier way by the syntax you propose, I'll be happy to change it accordingly.

**Comment by wahls** [comment]
> The kiss_fft files contained a lot of `int`'s for variables that should never take negative values. Hence, you normally call it with an `unsigned int` for such values, leading to an implicit type cast. I'm not sure if the range between `INT_MAX` and `UINT_MAX` is ever needed and usable in practice with the current solution. If not, an alternative solution would be a type cast with overflow check at every call of a kiss_fft function.

Is there not still a type cast given that `FNFT_UINT` currently resolves to `size_t` and not `unsigned int`?

> Regarding the loops: The reason is that if `i` is unsigned, `i>=0` always remains true, so the loops never end. This ugly solution just makes the previous implicit type cast explicit. If it can be solved in a prettier way by the syntax you propose, I'll be happy to change it accordingly.

That would be nice.

**Comment by PJ-Prins** [comment]
> Is there not still a type cast given that `FNFT_UINT` currently resolves to `size_t` and not `unsigned int`?

Good question. Indeed there was a type cast in`fnft__fft_wrapper.h`anyway, so please forget my previous answer. I've set kiss_fft back to original and changed the type cast in`fnft__fft_wrapper.h` to trace back why I needed to make those changes. Sadly, in that case there remain around 30 compiler warnings because of mixing `size_t` and `int` in the internals of kiss_fft. The only way to solve that is by changing the kiss_fft files. Shall I change the `int`'s to `size_t`(or FNFT_UINT ?) and indicate that on the top of those files?

> In `akns_fscatter`, I see a lot of for loops like this: `for (i=((INT)D)-1; i>=0; i--)`. Why not make `i` a `UINT` instead? The right way to write the for loop in such cases is `for (i=D-1; --i>0;)`, I believe.

The proposed syntax for the for-loops didn't work, but a slightly different syntax does now, with `UINT i`.

**Comment by wahls** [comment]
> > Is there not still a type cast given that `FNFT_UINT` currently resolves to `size_t` and not `unsigned int`?
> 
> Good question. Indeed there was a type cast in`fnft__fft_wrapper.h`anyway, so please forget my previous answer. I've set kiss_fft back to original and changed the type cast in`fnft__fft_wrapper.h` to trace back why I needed to make those changes. Sadly, in that case there remain around 30 compiler warnings because of mixing `size_t` and `int` in the internals of kiss_fft. The only way to solve that is by changing the kiss_fft files. Shall I change the `int`'s to `size_t`(or FNFT_UINT ?) and indicate that on the top of those files?

Good question. After thinking about it, switching to FNFT_UINT seems to be the right step. (It would be great to add quad precision to FNFT in the future. For that, the floating point data types in KissFFT have to be switched to FNFT_REAL and FNFT_COMPLEX.)

> > In `akns_fscatter`, I see a lot of for loops like this: `for (i=((INT)D)-1; i>=0; i--)`. Why not make `i` a `UINT` instead? The right way to write the for loop in such cases is `for (i=D-1; --i>0;)`, I believe.
> 
> The proposed syntax for the for-loops didn't work, but a slightly different syntax does now, with `UINT i`.

Great, thanks for figuring this out.

**Comment by wahls** [comment]
Looks good. Last comments: ` Chongelog` should be `Changelog`. Could you please add your name to indicate that these changes have not been made by the original authors? Right now that's not clear.

**Pull request merged**
