### PR TITLE
Release 0.4

### PR DESCRIPTION
**Pull request by wahls**

### CODE REVIEW

**Comment by ShrinivasJC** [comment]
From the documentation of `fnft_nsep` it is not clear which discretizations are supported. Should we add a list?

**Comment by wahls** [comment]
> From the documentation of `fnft_nsep` it is not clear which discretizations are supported. Should we add a list?

Yes, please. I also noted that in the README

```Version```

should be

```[Version](https://github.com/FastNFT/FNFT/releases)```

Could you please change that as well, in one go?

**Comment by ShrinivasJC** [comment]
On it.

**Comment by ShrinivasJC** [comment]
Complies correctly and all tests pass with gcc 7.5.0 with and without FFTW. `mex` files are generated correctly for R2019a. C and MATLAB examples run as expected. Documentation complies without issues with doxygen.

**Review by ShrinivasJC — APPROVED** [review]

**Comment by wahls** [comment]
Thank you! I will release and also update the online documentation.

**Pull request merged**
