### PR TITLE
Bug fix nsep

### PR DESCRIPTION
**Pull request by wahls**

### CODE REVIEW

**Comment by ShrinivasJC** [comment]
Can you please check the changelog once?

**Review by ShrinivasJC — APPROVED** [review]

**Comment by wahls** [comment]
> Can you please check the changelog once?

I made it a bit more explicit. Regarding commit 33b1b54:  D=2 is allowed as well, is it not?

By the way, should we put a comment somewhere in fnft_nsep.c which explains why D=power of two is currently required?

This might become handy at some point in the future...

**Comment by ShrinivasJC** [comment]
> > Can you please check the changelog once?
> 
> I made it a bit more explicit. Regarding commit [33b1b54](https://github.com/FastNFT/FNFT/commit/33b1b541e9c6fe168447d06f5c784ca42b03c2b7): D=2 is allowed as well, is it not?

You are right. I will correct the documentation to say `D>=2`

> By the way, should we put a comment somewhere in fnft_nsep.c which explains why D=power of two is currently required?
> 
> This might become handy at some point in the future...

I will add a few comments.

**Comment by wahls** [comment]
Many thanks!

**Pull request merged**
